version: '3.7'
services:
    app: 
      build: ./application1
      ports:
        - target: 5000
          published: 5000
          protocol: tcp 
      environment: 
        DATABASE_URI: ${DATABASE_URI}
        SECRET_KEY: ${SECRET_KEY}
    app2:
      build: ./application2
      ports:
        - target: 5001
          published: 5001
          protocol: tcp
    app3:
      build: ./application3
      ports:
        - target: 5002
          published: 5002
          protocol: tcp
    app4:
      build: ./application4
      ports:
        - target: 5003
          published: 5003
          protocol: tcp
