- hosts: docker
  become: true
  tasks:
    - name: Install Docker Requirements 
      apt:
        pkg:
        - apt-transport-https 
        - ca-certificates 
        - curl
        - gnupg-agent 
        - software-properties-common 
        state: latest 
        update_cache: true
     
    - name: Add GPG Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present 
      
    - name: Add apt-repository
      apt_repository:
        rep: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename|lower }} stable

    - name: Install Docker
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        state: latest
        update_cache: true
         
 
